# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

   
    steps:
      
    - name: Install dependencies
      run: yarn install
      
    - name: PROD_ENV Create
      run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env
        

      
    
